name: gmail_clone
description: A Gmail clone application with modern UI and features.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  file_picker: ^10.1.9
  flutter_quill: ^11.4.1
  intl: 0.19.0
  url_launcher: ^6.2.4
  path_provider: ^2.1.2
  image_picker: ^1.0.7
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  flutter_markdown: ^0.7.7+1
  timeago: ^3.6.1
  flutter_local_notifications: ^19.2.1
  permission_handler: ^12.0.0+1
  connectivity_plus: ^6.1.4
  flutter_secure_storage: ^10.0.0-beta.4
  http: ^1.2.0
  json_annotation: ^4.8.1
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700